# Generated by Django 4.2.10 on 2024-02-28 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("somrenkonto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarconfig",
            name="created_by",
            field=models.ForeignKey(
                help_text="who created this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="calendarconfig",
            name="modified_by",
            field=models.ForeignKey(
                help_text="who modified this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified_by",
            ),
        ),
        migrations.AlterField(
            model_name="renkontoevent",
            name="created_by",
            field=models.ForeignKey(
                help_text="who created this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="renkontoevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="who modified this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified_by",
            ),
        ),
        migrations.AlterField(
            model_name="workingday",
            name="created_by",
            field=models.ForeignKey(
                help_text="who created this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="workingday",
            name="modified_by",
            field=models.ForeignKey(
                help_text="who modified this object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified_by",
            ),
        ),
    ]
