# Generated by Django 2.2.16 on 2020-11-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0003_auto_20201109_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='renkontoevent',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Check if this event will last all day', verbose_name='All day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renkontoevent',
            name='campaign',
            field=models.ForeignKey(help_text='Campaing of this event', on_delete=django.db.models.deletion.CASCADE, to='somsolet.Campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='renkontoevent',
            name='event_type',
            field=models.CharField(choices=[('APPO', 'Appointment'), ('UNAVAIL', 'Unavailability'), ('AVAIL', 'Availability hours')], help_text='Type of this event, Appointment, Unavailability or Availability hours', max_length=64, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='renkontoevent',
            name='project',
            field=models.ForeignKey(help_text='Project of this event', on_delete=django.db.models.deletion.CASCADE, to='somsolet.Project', verbose_name='Project'),
        ),
    ]
