# Generated by Django 2.2.16 on 2020-11-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0005_auto_20201117_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarconfig',
            old_name='calendar_id',
            new_name='calendar',
        ),
    ]
