# Generated by Django 2.2.16 on 2020-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0006_auto_20201117_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfig',
            name='default_calendar_view',
            field=models.CharField(choices=[('Month View', 'dayGridMonth'), ('Week View', 'timeGridWeek'), ('Agenda View', 'listWeek'), ('Daily View', 'timeGridDay')], default='dayGridMonth', help_text='What will be the default view of the calendar', max_length=64, verbose_name='Default calendar View'),
        ),
    ]
