# Generated by Django 2.2.16 on 2020-11-18 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('somrenkonto', '0007_calendarconfig_default_calendar_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='when was created this object', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='last time this object updated', verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='when was deleted this object', null=True, verbose_name='deleted at')),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wendnesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], help_text='Calendar configuration associated whit this AvailableDay', max_length=64, verbose_name='Day')),
                ('start', models.TimeField(help_text='At what time starts your work journey', verbose_name='Start')),
                ('end', models.TimeField(help_text='At what time ends your work journey', verbose_name='End')),
                ('calendar_config', models.ForeignKey(help_text='Calendar configuration associated whit this AvailableDay', on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='somrenkonto.CalendarConfig', verbose_name='Calendar Config')),
                ('created_by', models.ForeignKey(help_text='who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='workingday_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('modified_by', models.ForeignKey(help_text='who modified this object', on_delete=django.db.models.deletion.CASCADE, related_name='workingday_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
