# Generated by Django 2.2.16 on 2021-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0008_workingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renkontoevent',
            name='event_type',
            field=models.CharField(choices=[('APPO', 'Appointment'), ('UNAVAIL', 'Unavailability'), ('AVAIL', 'Availability hours'), ('TECH', 'Technical visit'), ('INST', 'Installation work visit')], help_text='Type of this event, Appointment, Unavailability or Availability hours', max_length=64, verbose_name='Event type'),
        ),
    ]
