# Generated by Django 2.2.16 on 2021-06-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0009_auto_20210519_1639'),
        ('somrenkonto', '0009_renkontoevent_engineering'),
    ]

    operations = [
    ]
