# Generated by Django 2.2.16 on 2021-06-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somrenkonto', '0010_merge_20210609_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renkontoevent',
            name='project',
            field=models.ForeignKey(help_text='Project of this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='somsolet.Project', verbose_name='Project'),
        ),
    ]
