# Generated by Django 2.2.6 on 2019-10-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("somsolet", "0007_auto_20191015_1740"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="engineerings",
            field=models.ManyToManyField(
                related_name="campaigns",
                to="somsolet.Engineering",
                verbose_name="Engineering",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="engineering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign",
                to="somsolet.Engineering",
                verbose_name="Engineering",
            ),
        ),
    ]
