# Generated by Django 2.2.6 on 2019-10-29 08:10

from django.db import migrations


def make_many_engineerings(apps, schema):
    Campaign = apps.get_model('somsolet', 'Campaign')

    for campaign in Campaign.objects.all():
        campaign.engineerings.add(campaign.engineering)


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0008_auto_20191029_0903'),
    ]

    operations = [
        migrations.RunPython(make_many_engineerings),
    ]
