# Generated by Django 2.2.7 on 2020-05-20 14:30

from django.db import migrations


def postgres_migration_prep(apps, schema_editor):
    Technical_details = apps.get_model("somsolet", "Technical_details")
    fields = (
        "voltage",
        "tariff",
        "anual_consumption",
        "installation_model",
        "installation_singlephase_model",
        "installation_threephase_model",
        "acquire_interest",
        "client_comments",
        "engineering_comments",
        "bateries_brand",
        "bateries_model",
        "shadow_optimizer_brand",
        "shadow_optimizer_model",
        "panel_model",
        "inversor_model",
        "charger_manager_brand",
        "charger_manager_model",
        "electric_car_charger_brand",
        "electric_car_charger_model",
    )
    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Technical_details.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):
    dependencies = [
        ("somsolet", "0018_auto_20200520_1417"),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]
