# Generated by Django 2.2.7 on 2020-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0020_auto_20200520_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_details',
            name='bateries_brand',
            field=models.CharField(choices=[('empty', '---'), ('SONNEN', 'SONNEN'), ('BYD', 'BYD'), ('AMPERE', 'AMPERE'), ('LG', 'LG'), ('TESLA', 'TESLA')], default='empty', max_length=50, verbose_name='batery brand'),
        ),
    ]
