# Generated by Django 2.2.7 on 2020-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somsolet", "0022_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="count_foreseen_installations",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of foreseen installations"
            ),
        ),
    ]
