# Generated by Django 2.2.14 on 2020-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0023_campaign_count_foreseen_installations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='count_foreseen_installations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of planned installations'),
        ),
    ]
