# Generated by Django 2.2.16 on 2021-08-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0024_auto_20210811_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('rac_file', models.FileField(default='uploaded_files/legal_docs/rac_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded RAC File')),
                ('ritsic_file', models.FileField(default='uploaded_files/legal_docs/ritsic_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded RITSIC File')),
                ('cie_file', models.FileField(default='uploaded_files/legal_docs/cie_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded CIE File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalRegistrationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/legal_registration_docs/som.png', upload_to='uploaded_files/legal_registration_docs', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/offer/som.png', upload_to='uploaded_files/offer', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/permit/som.png', upload_to='uploaded_files/permit', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrereportStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/prereport/som.png', upload_to='uploaded_files/prereport', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondInvoiceStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/second_invoice/som.png', upload_to='uploaded_files/second_invoice', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignatureStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('upload', models.FileField(default='uploaded_files/contract/som.png', upload_to='uploaded_files/contract', verbose_name='Upload File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='notify',
        ),
        migrations.AddField(
            model_name='project',
            name='date_first_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Date First Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_last_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Date Last Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='engineering',
            field=models.ForeignKey(blank=True, help_text='Engineering responsable of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.Engineering', verbose_name='Engineering'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid_first_invoice',
            field=models.BooleanField(default=False, verbose_name='Paid First Invoice?'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid_last_invoice',
            field=models.BooleanField(default=False, verbose_name='Paid Last Invoice?'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_first_invoice',
            field=models.FileField(default='firstinvoice/som.png', upload_to='uploaded_files/firstinvoice', verbose_name='Upload First Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_last_invoice',
            field=models.FileField(default='lastinvoice/som.png', upload_to='uploaded_files/lastinvoice', verbose_name='Upload Last Invoice'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='notification_status',
            field=models.CharField(choices=[('empty status', 'Initial'), ('preregistered', 'Pre-Registered'), ('registered', 'Registered'), ('data downloaded', 'CCH data downloaded for analysis'), ('technical visit', 'Technical visit scheduled'), ('prereport review', 'Pre-Report review'), ('prereport', 'Pre-Report uploaded'), ('report review', 'Report review'), ('report', 'Report uploaded'), ('offer', 'Engineering offer'), ('offer_review', 'offer Review'), ('signature', 'Contract signature'), ('first payment', 'First Payment'), ('pending payment', 'Pending Payment'), ('permit', 'Construction permit'), ('pending installation date', 'Pending installation date'), ('date installation set', 'Date installation set'), ('installation in progress', 'Installation in progress'), ('end installation', 'End installation'), ('second invoice', 'Second Payment'), ('legal registration', 'Legal Registration'), ('last payment', 'Last Payment'), ('legalization', 'Legalization'), ('final payment', 'Final payment'), ('warranty payment', 'Warranty payment'), ('discarded', 'Discarded')], default='empty status', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.Campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid Preregistration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('empty status', 'Initial'), ('preregistered', 'Pre-Registered'), ('registered', 'Registered'), ('data downloaded', 'CCH data downloaded for analysis'), ('technical visit', 'Technical visit scheduled'), ('prereport review', 'Pre-Report review'), ('prereport', 'Pre-Report uploaded'), ('report review', 'Report review'), ('report', 'Report uploaded'), ('offer', 'Engineering offer'), ('offer_review', 'offer Review'), ('signature', 'Contract signature'), ('first payment', 'First Payment'), ('pending payment', 'Pending Payment'), ('permit', 'Construction permit'), ('pending installation date', 'Pending installation date'), ('date installation set', 'Date installation set'), ('installation in progress', 'Installation in progress'), ('end installation', 'End installation'), ('second invoice', 'Second Payment'), ('legal registration', 'Legal Registration'), ('last payment', 'Last Payment'), ('legalization', 'Legalization'), ('final payment', 'Final payment'), ('warranty payment', 'Warranty payment'), ('discarded', 'Discarded')], default='empty status', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='legal_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.LegalRegistrationStage', verbose_name='Legal registration certificate'),
        ),
        migrations.AddField(
            model_name='project',
            name='legalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.LegalizationStage', verbose_name='Legal certificate completed'),
        ),
        migrations.AddField(
            model_name='project',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.OfferStage', verbose_name='Offer data'),
        ),
        migrations.AddField(
            model_name='project',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.PermitStage', verbose_name='Permit data'),
        ),
        migrations.AddField(
            model_name='project',
            name='prereport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.PrereportStage', verbose_name='Prereport data'),
        ),
        migrations.AddField(
            model_name='project',
            name='second_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.SecondInvoiceStage', verbose_name='Second invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.SignatureStage', verbose_name='Signature data'),
        ),
    ]
