# Generated by Django 2.2.16 on 2021-09-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("somsolet", "0024_auto_20210811_1510"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalizationStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "rac_file",
                    models.FileField(
                        default="uploaded_files/legal_docs/rac_file.png",
                        upload_to="uploaded_files/legal_docs",
                        verbose_name="Uploaded RAC File",
                    ),
                ),
                (
                    "ritsic_file",
                    models.FileField(
                        default="uploaded_files/legal_docs/ritsic_file.png",
                        upload_to="uploaded_files/legal_docs",
                        verbose_name="Uploaded RITSIC File",
                    ),
                ),
                (
                    "cie_file",
                    models.FileField(
                        default="uploaded_files/legal_docs/cie_file.png",
                        upload_to="uploaded_files/legal_docs",
                        verbose_name="Uploaded CIE File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegalRegistrationStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/legal_registration_docs/som.png",
                        upload_to="uploaded_files/legal_registration_docs",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OfferStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/offer/som.png",
                        upload_to="uploaded_files/offer",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermitStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/permit/som.png",
                        upload_to="uploaded_files/permit",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrereportStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/prereport/som.png",
                        upload_to="uploaded_files/prereport",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecondInvoiceStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/second_invoice/som.png",
                        upload_to="uploaded_files/second_invoice",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignatureStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Date File"),
                ),
                ("check", models.BooleanField(default=False, verbose_name="Checked?")),
                (
                    "upload",
                    models.FileField(
                        default="uploaded_files/contract/som.png",
                        upload_to="uploaded_files/contract",
                        verbose_name="Upload File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="notify",
        ),
        migrations.AddField(
            model_name="project",
            name="date_first_invoice",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date First Invoice"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="date_last_invoice",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date Last Invoice"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="engineering",
            field=models.ForeignKey(
                blank=True,
                help_text="Engineering responsable of this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="somsolet.Engineering",
                verbose_name="Engineering",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_paid_first_invoice",
            field=models.BooleanField(
                default=False, verbose_name="Paid First Invoice?"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_paid_last_invoice",
            field=models.BooleanField(default=False, verbose_name="Paid Last Invoice?"),
        ),
        migrations.AddField(
            model_name="project",
            name="upload_first_invoice",
            field=models.FileField(
                default="firstinvoice/som.png",
                upload_to="uploaded_files/firstinvoice",
                verbose_name="Upload First Invoice",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="upload_last_invoice",
            field=models.FileField(
                default="lastinvoice/som.png",
                upload_to="uploaded_files/lastinvoice",
                verbose_name="Upload Last Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("empty status", "Initial"),
                    ("preregistered", "Pre-Registered"),
                    ("registered", "Registered"),
                    ("data downloaded", "CCH data downloaded for analysis"),
                    ("technical visit", "Technical visit scheduled"),
                    ("prereport review", "Pre-Report review"),
                    ("prereport", "Pre-Report uploaded"),
                    ("report review", "Report review"),
                    ("report", "Report uploaded"),
                    ("offer", "Engineering offer"),
                    ("offer_review", "offer Review"),
                    ("signature", "Contract signature"),
                    ("first payment", "First Payment"),
                    ("pending payment", "Pending Payment"),
                    ("permit", "Construction permit"),
                    ("pending installation date", "Pending installation date"),
                    ("date installation set", "Date installation set"),
                    ("installation in progress", "Installation in progress"),
                    ("end installation", "End installation"),
                    ("second invoice", "Second Payment"),
                    ("legal registration", "Legal Registration"),
                    ("last payment", "Last Payment"),
                    ("legalization", "Legalization"),
                    ("final payment", "Final payment"),
                    ("warranty payment", "Warranty payment"),
                    ("discarded", "Discarded"),
                ],
                default="empty status",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Campaign of this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.Campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client of this project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="somsolet.Client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_cch_download",
            field=models.DateField(
                blank=True,
                help_text="Date when cch curves were downloaded",
                null=True,
                verbose_name="Date CCH downloaded",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_delivery_certificate",
            field=models.DateField(
                blank=True,
                help_text="Date when the delivery certificate was issued",
                null=True,
                verbose_name="Date delivery certificate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_legal_docs",
            field=models.DateField(
                blank=True,
                help_text="Date when legal documentation was uploaded",
                null=True,
                verbose_name="Date legal certificate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_offer",
            field=models.DateField(
                blank=True,
                help_text="Date when offer was made",
                null=True,
                verbose_name="Date offer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_payment_som",
            field=models.DateField(
                blank=True,
                help_text="Date of the payment to SomEnergia was done",
                null=True,
                verbose_name="Date payment Som Energia",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_permit",
            field=models.DateField(
                blank=True,
                help_text="Date when work permit was uploaded",
                null=True,
                verbose_name="Date permit",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_prereport",
            field=models.DateField(
                blank=True,
                help_text="Date when prereport was uploaded",
                null=True,
                verbose_name="Date prereport",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_report",
            field=models.DateField(
                blank=True,
                help_text="Date when report was uploaded",
                null=True,
                verbose_name="Date report",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_signature",
            field=models.DateField(
                blank=True,
                help_text="Date when client signed the offer",
                null=True,
                verbose_name="Date signature",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_start_installation",
            field=models.DateField(
                blank=True,
                help_text="Start date of the installation works",
                null=True,
                verbose_name="Date start installation",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="discarded_type",
            field=models.CharField(
                choices=[
                    ("Not discarded", "---"),
                    ("technical", "technical"),
                    ("voluntary", "voluntary"),
                ],
                default="Not discarded",
                help_text="Discarded reason for this project",
                max_length=50,
                verbose_name="Discarded type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="final_payment",
            field=models.FloatField(
                blank=True,
                help_text="Amount of the final payment",
                null=True,
                verbose_name="Final payment",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_cch_downloaded",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if cch curves has been downloaded",
                verbose_name="CCH downloaded",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_date_set",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if there is a date set to start installation works",
                verbose_name="Installation date set?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_installation_in_progress",
            field=models.BooleanField(
                default=False,
                help_text="Check if installation works are in progress",
                verbose_name="Installation in progress?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_invalid_offer",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if offer is incorrect or not",
                verbose_name="Invalid Offer?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_invalid_prereport",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if prereport is incorrect or not",
                verbose_name="Invalid Prereport?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_invalid_report",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if report is incorrect or not",
                verbose_name="Invalid Report?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_offer_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicate if client has accepted the project offer",
                verbose_name="Offer accepted?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if preristration is paid",
                verbose_name="Paid Preregistration",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_payment_done",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if installation is allready paid",
                verbose_name="Payment done?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_signed",
            field=models.BooleanField(
                default=False,
                help_text="Check that indicates if client has already signed the offer",
                verbose_name="Signed contract?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Installation name",
                max_length=100,
                verbose_name="Installation",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_pending",
            field=models.FloatField(
                blank=True,
                help_text="Amount pending to pay",
                null=True,
                verbose_name="Payment pending",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preregistration_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the project preregistration",
                null=True,
                verbose_name="Preregistration Date",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="registration_date",
            field=models.DateField(
                blank=True,
                help_text="Date when de project was already registrated",
                null=True,
                verbose_name="Registration date",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("empty status", "Initial"),
                    ("preregistered", "Pre-Registered"),
                    ("registered", "Registered"),
                    ("data downloaded", "CCH data downloaded for analysis"),
                    ("technical visit", "Technical visit scheduled"),
                    ("prereport review", "Pre-Report review"),
                    ("prereport", "Pre-Report uploaded"),
                    ("report review", "Report review"),
                    ("report", "Report uploaded"),
                    ("offer", "Engineering offer"),
                    ("offer_review", "offer Review"),
                    ("signature", "Contract signature"),
                    ("first payment", "First Payment"),
                    ("pending payment", "Pending Payment"),
                    ("permit", "Construction permit"),
                    ("pending installation date", "Pending installation date"),
                    ("date installation set", "Date installation set"),
                    ("installation in progress", "Installation in progress"),
                    ("end installation", "End installation"),
                    ("second invoice", "Second Payment"),
                    ("legal registration", "Legal Registration"),
                    ("last payment", "Last Payment"),
                    ("legalization", "Legalization"),
                    ("final payment", "Final payment"),
                    ("warranty payment", "Warranty payment"),
                    ("discarded", "Discarded"),
                ],
                default="empty status",
                help_text="State of the project",
                max_length=50,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_contract",
            field=models.FileField(
                default="uploaded_files/contract/som.png",
                help_text="Contract file",
                upload_to="uploaded_files/contract",
                verbose_name="Upload Signed Contract",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_delivery_certificate",
            field=models.FileField(
                default="uploaded_files/delivery_certificate/som.png",
                help_text="Delivery certificate file",
                upload_to="uploaded_files/delivery_certificate",
                verbose_name="Upload delivery certificate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_offer",
            field=models.FileField(
                default="uploaded_files/offer/som.png",
                help_text="Offer file",
                upload_to="uploaded_files/offer",
                verbose_name="Upload Offer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_permit",
            field=models.FileField(
                default="uploaded_files/permit/som.png",
                help_text="Work permit file",
                upload_to="uploaded_files/permit",
                verbose_name="Upload Permit",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_prereport",
            field=models.FileField(
                default="uploaded_files/prereport/som.png",
                help_text="Prereport file",
                upload_to="uploaded_files/prereport",
                verbose_name="Upload Prereport",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="upload_report",
            field=models.FileField(
                default="uploaded_files/report/som.png",
                help_text="Report file",
                upload_to="uploaded_files/report",
                verbose_name="Upload Report",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="warning",
            field=models.CharField(
                choices=[
                    ("No Warn", "---"),
                    ("Not Payed", "Warning: Not payed"),
                    ("prereport", "Warning: Waiting for prereport"),
                    ("technical visit", "Warning: Waiting for technical visit"),
                    ("report", "Warning: Waiting for report"),
                    ("offer", "Warning: Waiting for offer"),
                    ("signature", "Warning: Waiting for signature"),
                    ("installation date", "Warning: Waiting for installation date"),
                    (
                        "finish installation",
                        "Warning: Installation deadline has passed",
                    ),
                    ("legal registration", "Warning: Pending registration reciept"),
                    ("legalization", "Warning: Waiting for legalization certificates"),
                    ("final payment", "Warning: Pending engineering payment"),
                    ("warranty payment", "Warning: Pending warranty payment"),
                ],
                default="No Warn",
                help_text="Items to be aware",
                max_length=100,
                verbose_name="Warning",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="warning_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the warning raised",
                null=True,
                verbose_name="Warning date",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="legal_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.LegalRegistrationStage",
                verbose_name="Legal registration certificate",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="legalization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.LegalizationStage",
                verbose_name="Legal certificate completed",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.OfferStage",
                verbose_name="Offer data",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="permit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.PermitStage",
                verbose_name="Permit data",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="prereport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.PrereportStage",
                verbose_name="Prereport data",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="second_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.SecondInvoiceStage",
                verbose_name="Second invoice",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="somsolet.SignatureStage",
                verbose_name="Signature data",
            ),
        ),
    ]
