# Generated by Django 2.2.17 on 2021-05-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0025_auto_20210208_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_first_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Date First Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_last_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Date Last Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid_first_invoice',
            field=models.BooleanField(default=False, verbose_name='Paid First Invoice?'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid_last_invoice',
            field=models.BooleanField(default=False, verbose_name='Paid Last Invoice?'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_first_invoice',
            field=models.FileField(default='firstinvoice/som.png', upload_to='uploaded_files/firstinvoice', verbose_name='Upload First Invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_last_invoice',
            field=models.FileField(default='lastinvoice/som.png', upload_to='uploaded_files/lastinvoice', verbose_name='Upload Last Invoice'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='notification_status',
            field=models.CharField(choices=[('empty status', 'Initial'), ('preregistered', 'Pre-Registered'), ('registered', 'Registered'), ('data downloaded', 'CCH data downloaded for analysis'), ('technical visit', 'Technical visit scheduled'), ('prereport review', 'Pre-Report review'), ('prereport', 'Pre-Report uploaded'), ('report review', 'Report review'), ('report', 'Report uploaded'), ('offer', 'Engineering offer'), ('offer review', 'offer Review'), ('signature', 'Contract signature'), ('first payment', 'First Payment'), ('pending payment', 'Pending Payment'), ('construction permit', 'Construction permit'), ('pending installation date', 'Pending installation date'), ('date installation set', 'Date installation set'), ('installation in progress', 'Installation in progress'), ('end installation', 'End installation'), ('legal registration', 'Legal Registration'), ('last payment', 'Last Payment'), ('legalization', 'Legalization'), ('final payment', 'Final payment'), ('warranty payment', 'Warranty payment'), ('discarded', 'Discarded')], default='empty status', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid Preregistration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('empty status', 'Initial'), ('preregistered', 'Pre-Registered'), ('registered', 'Registered'), ('data downloaded', 'CCH data downloaded for analysis'), ('technical visit', 'Technical visit scheduled'), ('prereport review', 'Pre-Report review'), ('prereport', 'Pre-Report uploaded'), ('report review', 'Report review'), ('report', 'Report uploaded'), ('offer', 'Engineering offer'), ('offer review', 'offer Review'), ('signature', 'Contract signature'), ('first payment', 'First Payment'), ('pending payment', 'Pending Payment'), ('construction permit', 'Construction permit'), ('pending installation date', 'Pending installation date'), ('date installation set', 'Date installation set'), ('installation in progress', 'Installation in progress'), ('end installation', 'End installation'), ('legal registration', 'Legal Registration'), ('last payment', 'Last Payment'), ('legalization', 'Legalization'), ('final payment', 'Final payment'), ('warranty payment', 'Warranty payment'), ('discarded', 'Discarded')], default='empty status', max_length=50),
        ),
    ]
