# Generated by Django 3.2.20 on 2023-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("somsolet", "0025_auto_20230620_1104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="engineering",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="project",
            name="registration_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Check to indicate if the email registration has been sent or not",
                verbose_name="Registration email sent: ",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="registration_email_sent_date",
            field=models.DateTimeField(
                help_text="Date when the registration email was sent",
                null=True,
                verbose_name="Registration email date",
            ),
        ),
    ]
