# Generated by Django 2.2.16 on 2021-06-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0026_auto_20210524_1623'),
        ('somsolet', '0025_auto_20210519_1639'),
    ]

    operations = [
    ]
