# Generated by Django 3.2.19 on 2023-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("somsolet", "0026_auto_20230714_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="sent_general_conditions_date",
            field=models.DateTimeField(
                help_text="Date when general conditions was sent",
                null=True,
                verbose_name="General conditions sent date",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="sent_general_conditions",
            field=models.BooleanField(
                default=False,
                help_text="Check to indicate if general conditions has been sent or not",
                verbose_name="General conditions sent: ",
            ),
        ),
    ]
