# Generated by Django 2.2.24 on 2021-11-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0027_auto_20211025_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='file',
        ),
        migrations.RemoveField(
            model_name='client',
            name='language',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sent_general_conditions',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.Client', verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='NotificationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='Telephone number')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('ca', 'Catalan'), ('gl', 'Galician'), ('eu', 'Euskara')], default='ca', max_length=5, verbose_name='Language')),
                ('sent_general_conditions', models.BooleanField(default=False, verbose_name='General conditions sent')),
                ('client', models.ForeignKey(blank=True, help_text='Client associated with this address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.Client', verbose_name='Client')),
                ('file', models.ManyToManyField(related_name='clients', to='somsolet.ClientFile', verbose_name='File')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='notification_address',
            field=models.ForeignKey(blank=True, help_text='Notification address of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.NotificationAddress', verbose_name='Notification Address'),
        ),
    ]
