# Generated by Django 2.2.16 on 2021-06-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0027_merge_20210609_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_technical_visit',
        ),
        migrations.AlterField(
            model_name='project',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.Campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Check that indicates if preristration is paid', verbose_name='Paid Preregistration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('empty status', 'Initial'), ('preregistered', 'Pre-Registered'), ('registered', 'Registered'), ('data downloaded', 'CCH data downloaded for analysis'), ('technical visit', 'Technical visit scheduled'), ('prereport review', 'Pre-Report review'), ('prereport', 'Pre-Report uploaded'), ('report review', 'Report review'), ('report', 'Report uploaded'), ('offer', 'Engineering offer'), ('offer review', 'offer Review'), ('signature', 'Contract signature'), ('first payment', 'First Payment'), ('pending payment', 'Pending Payment'), ('construction permit', 'Construction permit'), ('pending installation date', 'Pending installation date'), ('date installation set', 'Date installation set'), ('installation in progress', 'Installation in progress'), ('end installation', 'End installation'), ('legal registration', 'Legal Registration'), ('last payment', 'Last Payment'), ('legalization', 'Legalization'), ('final payment', 'Final payment'), ('warranty payment', 'Warranty payment'), ('discarded', 'Discarded')], default='empty status', help_text='State of the project', max_length=50, verbose_name='State'),
        ),
    ]
