# Generated by Django 2.2.24 on 2021-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0028_auto_20211125_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationaddress',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notificationaddress',
            name='sent_general_conditions',
        ),
        migrations.AddField(
            model_name='project',
            name='client_file',
            field=models.ManyToManyField(related_name='clients', to='somsolet.ClientFile', verbose_name='General conditions File'),
        ),
        migrations.AddField(
            model_name='project',
            name='sent_general_conditions',
            field=models.BooleanField(default=False, verbose_name='General conditions sent'),
        ),
    ]
