# Generated by Django 4.2.10 on 2024-02-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("somsolet", "0028_auto_20231130_1019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverycertificatestage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="deliverycertificatestage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="legalizationstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="legalizationstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="legalregistrationstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="legalregistrationstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="offeracceptedstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="offeracceptedstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="offerstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="offerstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="permitstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="permitstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="prereportstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="prereportstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="reportstage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="reportstage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="secondinvoicestage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="secondinvoicestage",
            old_name="check",
            new_name="_check",
        ),
        migrations.AlterField(
            model_name="signaturestage",
            name="check",
            field=models.BooleanField(
                db_column="check", default=False, verbose_name="Checked?"
            ),
        ),
        migrations.RenameField(
            model_name="signaturestage",
            old_name="check",
            new_name="_check",
        ),
    ]
