# Generated by Django 2.2.16 on 2021-06-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0028_auto_20210609_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engineering',
            field=models.ForeignKey(blank=True, help_text='Engineering responsable of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='somsolet.Engineering', verbose_name='Engineering'),
        ),
    ]
