# Generated by Django 2.2.16 on 2021-07-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0029_auto_20210623_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalizationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date File')),
                ('check', models.BooleanField(default=False, verbose_name='Checked?')),
                ('rac_file', models.FileField(default='uploaded_files/legal_docs/rac_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded RAC File')),
                ('ritsic_file', models.FileField(default='uploaded_files/legal_docs/ritsic_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded RITSIC File')),
                ('cie_file', models.FileField(default='uploaded_files/legal_docs/cie_file.png', upload_to='uploaded_files/legal_docs', verbose_name='Uploaded CIE File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='legalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='somsolet.LegalizationFile', verbose_name='Legal certificate completed'),
        ),
    ]
