# Generated by Django 2.2.24 on 2021-08-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somsolet', '0031_auto_20210810_1457'),
        ('somsolet', '0028_auto_20210810_1024'),
        ('somsolet', '0029_auto_20210812_1659'),
    ]

    operations = [
    ]
