from django.urls import path

from somrenkonto import views as somrenkonto_views
from . import views


urlpatterns = [
    path(
        'profile_engineering/',
        views.CampaignSetView.as_view(),
        name='campaign',
    ),
    path(
        'client/<int:pk>/',
        views.ClientView.as_view(template_name='somsolet/client_detail.html'),
        name='client',
    ),
    path(
        'download_cch/<int:pk>/',
        views.DownloadCch.as_view(),
        name='download_cch'
    ),
    path(
        'technical_details/<int:pk>/',
        views.TechnicalDetailsView.as_view(),
        name='technical_details'
    ),
    path(
        'technical_campaign/<int:pk>/',
        views.TechnicalCampaignsView.as_view(),
        name='technical_campaign'
    ),
    path(
        'project/<int:pk>/',
        views.ProjectView.as_view(),
        name='project'),
    path(
        'prereport/<int:pk>/',
        views.PrereportView.as_view(),
        name='prereport'
    ),
    path(
        'report/<int:pk>/',
        views.ReportView.as_view(),
        name='report'
    ),
    path(
        'offer/<int:pk>/',
        views.OfferView.as_view(),
        name='offer'
    ),
    path(
        'signed_contract/<int:pk>/',
        views.SignatureView.as_view(),
        name='signed_contract'
    ),
    path(
        'construction_permit/<int:pk>/',
        views.ConstructionPermitView.as_view(),
        name='construction_permit'
    ),
    path(
        'installation_date/<int:pk>/',
        views.InstallationDateView.as_view(),
        name='installation_date'
    ),
    path(
        'delivery_certificate/<int:pk>/',
        views.DeliveryCertificateView.as_view(),
        name='delivery_certificate'
    ),
    path(
        'legalization/<int:pk>/',
        views.LegalizationView.as_view(),
        name='legalization'
    ),
    path(
        'legal_registration/<int:pk>/',
        views.LegalRegistrationView.as_view(),
        name='legal_registration'
    ),

    # Som Renkonto
    path(
        'somrenkonto',
        somrenkonto_views.CalendarView.as_view(),
        name='somrenkonto',
    ),
    path(
        'somrenkonto/events',
        somrenkonto_views.SomRenkontoEventView.as_view(),
        name='new_event'
    ),
    path(
        'somrenkonto/calendar/<int:pk>',
        somrenkonto_views.EditCalendarView.as_view(),
        name='edit_calendar'
    )
]
